from classicML.api.models import BackPropagationNeuralNetwork
from classicML.api.models import BPNN
from classicML.api.models import DecisionTreeClassifier
from classicML.api.models import LogisticRegression
from classicML.api.models import LinearDiscriminantAnalysis
from classicML.api.models import LDA
from classicML.api.models import RadialBasisFunctionNetwork
from classicML.api.models import RBF
from classicML.api.models import SupportVectorClassifier
from classicML.api.models import SVC