name: PyPI

on:
  release:
    types: [published, created]

jobs:
  deploy:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15]
        python-version: [3.7, 3.8, 3.9]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Before install
      run: |
        # 安装 setuptools, wheel, twine和pybind11
        python3 -m pip install --upgrade pip;
        pip install setuptools wheel twine pybind11==2.8.0;
        # 安装 eigen3
        if [ "${{ matrix.os }}" = "macos-10.15" ]; then
          rm -rf /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core;
          brew update;
          brew install eigen;
        else
          sudo apt update;
          sudo apt install -y libeigen3-dev;
          sudo cp -r /usr/include/eigen3 /usr/local/include/eigen3;
        fi
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python3 setup.py sdist bdist_wheel
        # 修改Linux下的包名
        if [ "${{ matrix.os}}" = "ubuntu-18.04" ]; then
          filename=`ls dist/*.whl`;
          newfilename=${filename/"linux"/"manylinux2010"};
          mv $filename $newfilename;
        fi
        python3 -m twine upload --repository pypi dist/* --skip-existing;