name: win-PyPI

on:
  release:
    types: [published, created]

jobs:
  deploy:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]
        python-version: [3.7, 3.8, 3.9]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Before install
      run: |
        # 安装 setuptools, wheel, twine和pybind11
        python3 -m pip install --upgrade pip;
        pip install setuptools wheel twine pybind11==2.8.1;
        # 安装 eigen3
        vcpkg install eigen3:x64-windows;
    - name: Build
      run: |
        python3 setup.py sdist bdist_wheel;
    - name: Publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python3 -m twine upload --repository pypi dist/* --skip-existing;